development:
  base_url: https://rest.developer.yodlee.com/services/srest/restserver/v1.0/
  username: sbCobryanam6480
  password: f808d945-8dba-4a12-85c6-c6ccfb525557
  register_users: true

test:
  base_url: https://rest.developer.yodlee.com/services/srest/restserver/v1.0/
  username:
  password:
  register_users: false

production:
  base_url:
  username:
  password:
  register_users: true
